/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

class App {
    val greeting: String
        get() {
            return "Hello Kotlin!"
        }
}

fun main() {
    println("Hello Kotlin")
    println("Hola soy Santino y hoy es Martes 22 de Abril")
}
